### PR TITLE
Fix CA errors.

### LINKED ISSUE #264: Build.cmd fails with locale-specific mispelled words
The build.cmd in the Dev branch fails on my machine with misspelled words ```Signaling``` and ```Startup``` from Code Analysis. My machine is set to the UK locale and fails. Another person here tried it here with a German locale and it works.

I suspect that these words are valid US words and that's why it's ok.

The build should not be failing depending on the locale of the build machine.

### PR DESCRIPTION
**Pull request by isaacabraham**
Fix #264. Although perhaps another solution should be looked at to investigate that a bit further.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@isaacabraham__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by fabiocav** [comment]
Adding valid en-us words to the custom dictionary to make this work in different locales is fragile (as it would not prevent future build issues in different locales unless we're testing against all) an would become unmanageable if we are to address variations for other supported code analysis spell checking locales (e.g. Initialize vs Initialise for en-AU and many others we'll run into)

The correct fix for this is to set the CodeAnalysisCulture project property to en-US, which is what we want to validate against.

**Comment by forki** [comment]
or to just remove that completely. just saying

**Comment by isaacabraham** [comment]
@fabiocav Yes, this is the sort of thing I was alluding to in my PR when I said "another solution". Where does one set that culture property?

**Comment by fabiocav** [comment]
@isaacabraham, you can set the CodeAnalysisCulture property in the project file (i.e. `<CodeAnalysisCulture>en-US</CodeAnalysisCulture>`)

**Comment by isaacabraham** [comment]
@fabiocav done

**Comment by mathewc** [comment]
Guys, what is the status of this PR? @fabiocav is this good to merge?

**Comment by fabiocav** [comment]
Yes, this is good to merge.

**Comment by mathewc** [comment]
Merged, thanks :)

**Pull request closed without merging**
