### PR TITLE
Setting maxRequestLength and fixing nuspec

### PR DESCRIPTION
**Pull request by mathewc**
Adding missing package dependency, and also addressing https://github.com/Azure/azure-webjobs-sdk-script/issues/322

### CODE REVIEW

**Comment by davidebbo** [comment]
:shipit:

**Comment by paulbatum** [comment]
I see this is using the same value the kudu is configured to use. But why was this a good change to make? Shouldn't we be pushing people towards sending large data to functions via blobs, etc?

**Comment by davidebbo** [comment]
Yes, we should encourage good patterns, but at the same time should not artificially block them. If they run a regular site, they get that flexibility.

**Comment by paulbatum** [comment]
@davidebbo You're making a decision for someone one way or another. If I'm paying for gbit/sec I am not sure I want someone to be able to send 400mb requests to my function...

**Comment by davidebbo** [comment]
That's an interesting point. With Kudu, only the owner can send requests. Here, in the case of an unauthenticated function, that may become a concern. The ASP.NET default of 4096KB (unit is KB) is too low (it was set 15 years ago!), but maybe we should raise it to a more reasonable number, like 16384KB, and not that mostly infinite number we use in Kudu.

**Comment by fabiocav** [comment]
I share Paul's concerns and like the last option a lot better. We can adjust this as we go, but it would be good to start safe, principally considering the memory constraints functions execute under.

**Comment by davidebbo** [comment]
Yep, let's make it 16MB which feels like a decent place to be.

**Comment by tcjustin** [comment]
Just to chime in (I'm the one that opened the original ticket). For my use case the 16MB limit will probably be fine as the largest uploads I'm going to deal with will be text based and 16MB is probably ok in that case. If I was doing an app that dealt with image uploading and processing 16MB might be too small. I get that I could write my app to first upload to blob storage but capping at 16MB still seems arbitrarily small to me given that the ram limit starts at 128MB. If I had to choose I'd rather see something like 64MB or even a sliding scaled based on the ram size I pick for my function.

To Paul's comment directly I thought we choose the ram size per function and have to pay for that regardless of how much ram is actually used (I know that's how AWS Lambda works). My thought was if you pick 128MB for the ram size the function errors out as it exhausts it's allocated ram. Unless something has changed on the pricing front I'm not aware of.

**Pull request merged**
