### PR TITLE
Don't create empty ImmutableArray only to create a builder from it

### PR DESCRIPTION
**Pull request by forki**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@forki__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by forki** [comment]
dear @azurecla why do you require my employer to sign? Can you please use the same process like https://github.com/Microsoft/visualfsharp ?

**Comment by fabiocav** [comment]
@forki , as mentioned by @davidebbo on #279 , this is CLA process applies to the entire Azure organization and isn't something we'll be changing. Sorry if that's more painful than you expected, but let's just get this out of the way so you come party with us :)

**Comment by fabiocav** [comment]
The changes look good 👍 

Just a small clarification, as the PR title implies the creation of an empty `ImmutableArray`, the change is cosmetic. It does clean up the code, but there's no real performance/efficiency difference between the current code and the proposed changes. `Empty` does not create a new `ImmutableArray` and the internal implementation of `CreateBuilder` actually calls `Empty` *and* `ToBuilder` through another indirection.

**Comment by forki** [comment]
@faiocav if it's the same CLA process for azure then I propose you get rid of it in the whole org. This is painful for many devs. This was discussed in devdiv like a million times and changing the CLA process was a big success. I'd love to log this issue in some global discussion issue tracker. If the roslyn/VF# project got rid of this then you can too. I mean you clearly want to make it contributors as easy as possible. Going through employer management approval is a showstopper for many many devs.


Regarding this PR - I didn't not imply any perf changes. TBH I don't think using a builder will change that much in this case. Transient mutable objects are often a win if you have lots of elements, but most of the time they are just not needed. Anyways here it was just hurting my yes a bit to go from ImmutableArray to Builder and back to ImmutableArray.

**Comment by forki** [comment]
"I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer" -  that's option that is missing in azure CLA. It is available in CLA.Microsoft.com

**Comment by davidebbo** [comment]
I pinged @martinwoodward on twitter ([here](https://twitter.com/davidebbo/status/723871596599898112)) to comment on the CLA part.

**Comment by davidebbo** [comment]
FYI, I have started a mail thread with @martinwoodward, @forki  and @KevinRansom to discuss the CLA part.

**Comment by mathewc** [comment]
What is the status of this PR? I believe David fixed the CLA issues.

**Comment by fabiocav** [comment]
@forki closing this since the work to rebase and deal with possible conflicts will be larger than submitting another PR with the change in the existing codebase, but feel free to reopen if you wish.
David has updated the CLA process and I hope it addresses the issues you had. Really look forward to future contributions from you and thanks for your patience while we worked through some of the issues.

**Pull request closed without merging**
