### PR TITLE
Fixing assembly dependency resolution

### LINKED ISSUE #200: Unable to load Private dll from bin folder during execution
Function app:
https://functionsb28e57ff.scm.azurewebsites.net/DebugConsole

I created a bin folder , and uploaded the dll files here
D:\home\site\wwwroot\TimerTriggerCSharp1\bin>

and am referencing some dlls there using
#r "Microsoft.Data.Tools.Schema.Sql.dll" 

The function compiles, but during execution, gives this error. The dll is present in the bin folder.
What am I missing ?

2016-03-30T23:02:00.990 Exception while executing function: Functions.TimerTriggerCSharp1. mscorlib: Exception has been thrown by the target of an invocation. ƒ-TimerTriggerCSharp1#ℛ*5ed3b47c-9016-494f-9e8b-b2478647f62e#3-0: **Could not load file or assembly 'Microsoft.Data.Tools.Schema.Sql, Version=13.0.0.0**, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
.

### LINKED ISSUE #204: C#: Dependencies-of-dependencies not resolved correctly
Example: Try adding Twilio as a nuget reference and when running you'll get 'RestSharp not found' errors. This affects nuget references as well as sticking both dependencies in the private /bin directory. 

@fabiocav has a lead already on the issue -- filing this to track.

### PR DESCRIPTION
**Pull request by fabiocav**
Resolves #204 
Resolves #200

### CODE REVIEW

**Comment by brettsam** [comment]
Can you give a little background on what the issue was and how this addresses it?

**Comment by fabiocav** [comment]
A function context is established for assembly loading, which enables us to properly resolve private assemblies and NuGet assembly references for a given function. When loading an indirect dependency, we were failing to resolve the context and therefore, failing to load those assemblies. With the changes in this PR, the context keeps track of the dependencies it loads, allowing us to correctly resolve the context when indirect dependencies are requested, which we then use to resolve those dependencies.

**Comment by fabiocav** [comment]
Updated comment as this also resolves issue #200

**Comment by mathewc** [comment]
Looks OK to me. How did you test this? I understand adding regression tests for this might be difficult without making changes to make the loader more testable. If you think it would take to long to get tests in place, we can add to backlog.

**Comment by fabiocav** [comment]
The tests were indeed fairly manual. If you don't object, I'll create an issue to address this in a separate PR which will include some of the other code refactoring to better enable testing.

**Comment by mathewc** [comment]
Sounds good.

**Pull request merged**
