### PR TITLE
Updating extensions nuget packages

### PR DESCRIPTION
**Pull request by brettsam**
@safihamid, @emilcicos -- I had to update ApiHub.Sdk to 0.6.6-alpha in order to update the ApiHub extension. Let me know if you want me to roll that back.

### CODE REVIEW

**Comment by mathewc** [comment]
We're going to have to do this update again soon once Emil's stuff is in Extensions. We're waiting on that.

**Comment by emilcicos** [comment]
ApiHub.Sdk to 0.6.6-alpha is fine.

**Comment by brettsam** [comment]
If it keeps things less confusing, I can rescind this PR and wait for Emil's (assuming it'll be included in the next release); I can test the changes privately.

**Comment by mathewc** [comment]
Moved to latest Extensions here: https://github.com/Azure/azure-webjobs-sdk-script/commit/c0f6516c0f3934fbfc99c302d988a74022bdbcb8

**Pull request closed without merging**
