### PR TITLE
Remove old metric ETW event from MetricsEventManager

### PR DESCRIPTION
**Pull request by akurmi**

### CODE REVIEW

**Comment by mathewc** [comment]
Thanks. Looks good. Is this safe to merge now?

**Comment by akurmi** [comment]
Yes, all MetricsEventManager test cases passed locally for me. Let's wait for all test cases to finish here before merging it :).

**Comment by mathewc** [comment]
You got an ack from the monitoring team that they don't rely on this any more?

**Comment by akurmi** [comment]
I looked at the source code and it looks like this event is not being used anymore. Hang on, I guess I messed up the commit as CI failed.

**Comment by mathewc** [comment]
Merged

**Pull request closed without merging**
