### PR TITLE
setting a DefaultConnectionLimit in dynamic sku

### PR DESCRIPTION
**Pull request by brettsam**
An initial improvement related to #850 until we have a true way for customers to update this themselves.

Right now we impose no limit, yet the Dynamic sandbox has a limit of 300 connections. This makes it quite easy to make requests in a loop and surpass that limit. By lowering the .NET limit to 250 (which gives a little headroom below the 300 limit), we can eliminate the scenario where a lot of requests to a single host are hitting the sandbox limit. Instead, those requests will be queued up and made when a connection becomes available.

Another scenario that is not fully protected by this is one where requests to many different hosts are being sent. The `DefaultConnectionLimit` applies to each created `ServicePoint` -- and a new `ServicePoint` is created for each host.

For a test, I had some code in a function that simultaneously downloaded 5000 ~92kb files:

    var result = container
            .ListBlobs(null, true, BlobListingDetails.Metadata)
            .OfType<CloudBlockBlob>()
            .Select(async x => await x.DownloadTextAsync());

Before the change, this hit the socket exception. After the change, it completed in ~107s.

### CODE REVIEW

**Comment by brettsam** [comment]
@mamaso -- I know you just looked at this a bunch; would be good to get your thoughts.

**Comment by mamaso** [comment]
I think this is a good initial fix. It could cause timeouts instead of socket exceptions, but I'd consider than an improvement.

It won't prevent us from hitting the limit due to multiple endpoints * many connections, but it should cover a large number of common cases (such as making a request to a single endpoint with a per-execution http client).

**Comment by mamaso** [comment]
Another question - what is the connection limit in dedicated? Should this be dynamic only?

It would be nice to investigate if service point manager had any hooks, or perhaps write our own in order to warn if approaching the limit.

**Comment by brettsam** [comment]
The connection limit in ASP.NET apps is `Int32.MaxValue`. My understanding is that you'll start to get naturally queued in that case as you'd run into resource constraints at the machine level. The way the sandbox shuts you down without any warning (or queueing) is the issue we're hitting here. If we see someone hit this in dedicated, let's revisit.

The ultimate goal is to allow for a (close-to) process startup-callback where you can write this code on your own to fine-tune any global settings. But this gets us to a better default while we work out those details.

While ServicePointManager doesn't have a callback, we do have a way to monitor your connections (and the limit): https://github.com/Azure/azure-webjobs-sdk-script/blob/dev/src/WebJobs.Script/Diagnostics/HostPerformanceManager.cs#L43. But that is only used by the HTTP request queueing piece that @mathewc added fairly recently. I want to see if there's a way that we can use this for more general-purpose error reporting as well. For example, if we detect a ScriptHost error (or even a Function error?), can we quickly check your connection count against the limit and log an informational warning?

**Comment by mamaso** [comment]
Agree with all your previous points, piggybacking on host perf manager sounds promising.

One clarification - currently this limit is in place for dynamic, but should we add the limit to both dynamic & dedicated sku? Alternately, what if we made this a setting in host.json for configuration purposes?

**Comment by brettsam** [comment]
Doing it on dedicated may unexpectedly lower some people's throughput so I'd rather not do it across-the-board. I've not seen anyone hitting any issues in dedicated, and the fact that ASP.NET doesn't supply a limit by default makes me hesitant to impose one.

A host.json setting wouldn't work b/c you'd need the entire process recycled, not just the host. I was thinking about opening it up to an app setting (which would recycle the process), but I want to talk it over with everyone first -- I don't want to open up a new pattern for a single setting. I'd rather have a more general way to let people modify global settings like this (assuming there are others). I'll follow up on issue #850 to try to come to some resolution.

Doing this at least gets us some benefit while we discuss the right approach.

**Pull request merged**
