### PR TITLE
[WiP] Helping Don - PR just to trigger CI

### PR DESCRIPTION
**Pull request by tpetricek**

### CODE REVIEW

**Comment by fabiocav** [comment]
:)

**Comment by fabiocav** [comment]
@tpetricek if the Mobile test is causing you trouble, I can take a look to see if can pinpoint the root cause. I can also send you details on how to run that e2e test locally (with a test environment you can use)

**Comment by tpetricek** [comment]
/cc @dsyme 

It's the last one causing us troubles :-). We're not entirely sure what the issue is - I think that for some reason the second part of the test (`MobileTableIn` function) is not correctly triggered. Based on 815e0b4,  it seems that `MobileTableOut` is triggered correctly - if we set the expected value to the one that `MobileTableIn` is supposed to produce, then the test passes.

Our last theory is that this is caused by the fact that we are reusing the same queue name (and there are multiple functions that listen on the queue - so perhaps this triggers Node/C# function instead of the F# function?). But I guess that's not the case - that's what I was trying to figure out in d0dee95.

So there must be something else...

**Comment by fabiocav** [comment]
The tests shouldn't be running in parallel, but it's a good idea to change the tests to use unique queues and avoid possible collisions. We've done that with most of the other tests, but I guess this one slipped.

I'll pull your changes and run that test to see what if I can find more information about what is going on.

**Comment by fabiocav** [comment]
@tpetricek I'm assuming all the changes were in the fsharp branch, so I'm closing this. Let me know if that wasn't the case.

**Comment by tpetricek** [comment]
@fabiocav Correct! This was just my scratchpad for making you pay more for CI :100: Thanks for merging the main one!

**Pull request closed without merging**
