### PR TITLE
Setting AppVeyor tests to properly report failure

### PR DESCRIPTION
**Pull request by brettsam**

### CODE REVIEW

**Comment by brettsam** [comment]
@fabiocav / @mamaso -- is this the right fix to get AppVeyor tests reporting failure? I see we've had a bunch of failures recently and people probably don't notice b/c the run reports green.

**Comment by mamaso** [comment]
Oh god, the horror. But yep that looks right!

Can you add an intentionally failing test to the tests so we can test this? :D lmao

**Comment by brettsam** [comment]
I don't have to -- something is wrong with the CosmosDBTrigger tests and they've been failing. It looks like something weird -- another host is running in the background delaying processing. But I'm not sure why that background host hasn't stopped before the next text class runs. @ealsur and I are investigating.

**Comment by fabiocav** [comment]
Thank you for taking care of this. I was submitting the "approve" feedback, but this got merged just as I was about to hit the button :)

**Pull request merged**
