### PR TITLE
[WIP] [F#] add failing twilio test

### PR DESCRIPTION
**Pull request by dsyme**
Add a failing test for https://github.com/Azure/azure-webjobs-sdk-script/issues/819

### CODE REVIEW

**Comment by dsyme** [comment]
@lindydonna @fabiocav @christopheranderson Can you enable full CI on this please? Thanks

**Comment by dsyme** [comment]
OK, the test is failing, that's good in this context.  I'll close this and we'll add the (hopefully passing) test to #893

**Comment by dsyme** [comment]
Microsoft.Azure.WebJobs.Script.Tests.CSharpEndToEndTests.MobileTables aso failed in CI, but that appears unrelated, just a CI glitch

**Comment by fabiocav** [comment]
That test is known to fail every once in a while. It's on our radar to get it stable.

**Pull request closed without merging**
