### PR TITLE
updating extensions nugets to 10382

### PR DESCRIPTION
**Pull request by brettsam**
Specifically taking the PR to fix a timer bug: https://github.com/Azure/azure-webjobs-sdk-extensions/pull/167

### CODE REVIEW

**Comment by davidebbo** [comment]
:shipit:

**Comment by brettsam** [comment]
Actually, I'm going to fix something else before committing this. It looks like we had a Core SDK nuget update that went directly to Script, skipping Extensions. Extensions and Script should have the same Core SDK dependencies, so I'll generate a new Extensions nuget and then update this.

**Comment by davidebbo** [comment]
Didn't we also want to match storage with what bot is using?

**Comment by brettsam** [comment]
Just saw that mail; I'll get on it.

**Comment by mathewc** [comment]
:ship:

**Comment by brettsam** [comment]
Closing this and re-opening a new one with new updated dependencies.

**Pull request closed without merging**
