### PR TITLE
Disposing of resources used by function invokers when host shuts down.

### LINKED ISSUE #47: Functions can get saved multiple time on each Save
After playing with a function for a while, it can get into a state where each Save causes multiple compilations. e.g. all at once:

```
2016-03-03T20:44:08 Script for function 'cs' changed. Reloading.
2016-03-03T20:44:08 Script for function 'cs' changed. Reloading.
2016-03-03T20:44:08 Script for function 'cs' changed. Reloading.
2016-03-03T20:44:08 Script for function 'cs' changed. Reloading.
2016-03-03T20:44:08 Script for function 'cs' changed. Reloading.
2016-03-03T20:44:08 Script for function 'cs' changed. Reloading.
2016-03-03T20:44:08 Script for function 'cs' changed. Reloading.
2016-03-03T20:44:08 Compiling function script.
2016-03-03T20:44:08 Compiling function script.
2016-03-03T20:44:08 Compiling function script.
2016-03-03T20:44:08 Compiling function script.
2016-03-03T20:44:08 Compiling function script.
2016-03-03T20:44:08 Compiling function script.
2016-03-03T20:44:08 Compiling function script.
2016-03-03T20:44:08 Compiling function script.
2016-03-03T20:44:08 Compiling function script.
```

### PR DESCRIPTION
**Pull request by fabiocav**
Resolves #47

### CODE REVIEW

**Comment by fabiocav** [comment]
@mathewc , @davidebbo , since we moved the file watcher to the base invoker class, this addresses potential issues with the other languages as well.

**Comment by davidebbo** [comment]
Weird that `GlobalSuppressions.cs` is treated as a binary file!?

**Comment by ahmelsayed** [comment]
maybe because it's UTF-16

**Comment by davidebbo** [comment]
@ahmelsayed  Ah, we should change that.

**Comment by davidebbo** [comment]
The Dispose change looks straightforward enough, so go ahead.

**Pull request merged**
