### PR TITLE
Updating F# compiler service

### LINKED ISSUE #1931: Update F# compiler service references

### PR DESCRIPTION
**Pull request by fabiocav**
Resolves #1931

### CODE REVIEW

**Comment by fabiocav** [comment]
@dsyme would you mind taking a quick look at this? Thank you!

**Comment by fabiocav** [comment]
@dsyme just ran a couple of tests and it does seem like we're getting hit by this:
https://github.com/Microsoft/visualfsharp/issues/2257

Unfortunately, looks like Json.NET 9.0.2 was never released (went from that beta to the next major version). Upgrading Json.NET to 10.x might be difficult, as it is a potential breaking change. We _could_ push to the 9.0.2-beta, but ideally we'd be on a stable release.

**Comment by fabiocav** [comment]
Maybe we can get some help from @JamesNK here. 

We can't safely upgrade to 10.x, as this would be an in place upgrade. This might be asking a lot, but what are the chances you'd be able to publish a stable 9.x release that includes that fix (essentially what you had in 9.0.2-beta)?

**Comment by JamesNK** [comment]
Releasing a new version isn't quick and for a single project it would take up too much of my time.

**Comment by fabiocav** [comment]
@JamesNK that's understandable. Had to ask anyway :)

**Pull request closed without merging**
