### PR TITLE
updating extensions dependencies to 10306

### PR DESCRIPTION
**Pull request by brettsam**
This absorbs the "Setting" suffix convention for attribute properties that point to app settings. I did not change any binding metadata properties here, so this is not a breaking change.

### CODE REVIEW

**Comment by brettsam** [comment]
@mathewc -- I didn't get to merge this before I went OOF last week. Any objections?

**Comment by mathewc** [comment]
Are you dependent on this for anything immediately? The reason I ask is that in my extensibility PR (hoping to get in in a few days), I'll be updating all the refs anyways. So if you don't need this now, I'd say hold off.

**Comment by brettsam** [comment]
I don't need it ASAP -- but there were a few 'ConnectionString' -> 'ConnectionStringSetting' (and similar) refactors that had to be made in addition to the straight nuget stuff. It was pretty straightforward but just wanted to call it out. If you wanna tackle it, that's fine -- I'll retract this.

**Comment by mathewc** [comment]
Yeah, I see you're modifying a bunch of files that my PR deletes. I'll handle it, thanks.

**Comment by brettsam** [comment]
Oh of course. Sounds good.

**Pull request closed without merging**
