### PR TITLE
Fixing function.json schema

### PR DESCRIPTION
**Pull request by fabiocav**
Moving properties to the appropriate (root) location.

### CODE REVIEW

**Comment by fabiocav** [comment]
@mamaso rushed this one a bit... but FYI.

**Comment by mamaso** [comment]
yeesh, so this was per binding instead of per function.json? Good catch

**Comment by fabiocav** [comment]
I've submitted a PR to schema store to have this fixed ASAP.

**Comment by fabiocav** [comment]
@ahmelsayed found the issue.

**Pull request merged**
