### PR TITLE
Integrate dev --> fsharp 

### PR DESCRIPTION
**Pull request by dsyme**
Integrate dev --> fsharp (independent of #544)

### CODE REVIEW

**Comment by dsyme** [comment]
@fabiocav Please merge this please, thanks

**Comment by christopheranderson** [comment]
🎉 It's happening 🎉

**Comment by dsyme** [comment]
@fabiocav Some tests are failing, I'm not sure of the state of the "fsharp" branch w.r.t. CI prior to this.  We could do a no-op PR to "fsharp" to find out I suppose.  But I think we could also assume that #544 fixes the tests.

**Comment by fabiocav** [comment]
I'll merge this in to bring it current and we can work on bringing #544 in.

**Comment by fabiocav** [comment]
Merged

**Comment by dsyme** [comment]
thanks!

**Pull request merged**
